#!/usr/bin/env bash
# script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
ps -uh -p "6596"
ps -uh --ppid "6596"
