#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process.
# Requirements:
# * You must use kill
input=$(pgrep -a bash  | grep 4-to_infinity_and_beyond)
counter=0

for x in $input
do
	if [ $counter -eq 0 ]; then
		kill "$x"
	fi
	((counter++))
done
