#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=0
while [ $counter -lt 20 ]
do
	((counter += 1))
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
	esac
done

