#!/usr/bin/env bash
# script that gives you information about the school file.

school_file="./school"

if [ -e "$school_file" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
fi
if ! [ -s "$school_file" ]; then
	echo "school file is empty"
else 
	echo "school file is not empty"
fi
if [ -f "$school_file" ]; then
	echo "school is a regular file"
fi
